site_name: 接口文档 # 文档站点的标题*
site_url: "https://example.com" #站点 URL 链接*
site_author: freely-code #站点作者
site_description: "接口文档" #站点描述
copyright: "Copyright © 2024 fleely-code" #版权信息
repo_url: "https://github.com/freely-code/server" #站点仓库 URL
repo_name: "一切为了自由" #站点仓库名称
site_dir: site #构建目录
theme: # 主题的配置选项
  name: material # 主题名称
  icon:  #图标选项
    logo: material/github   #图标路径
  language: zh #语言设置
  palette: #风格
    - media: "(prefers-color-scheme: light)" #亮色
      scheme: "default"    #根据系统设置
      #主要颜色 red|红色 pink|粉色 purple|紫色 deep-purple|深紫色 indigo|靛蓝色 blue|蓝色 light-blue|浅蓝色 cyan|青色 teal|蓝绿色 lime|黄绿色 deep-orange|深橙色 brown|棕色 grey|灰色 blue-grey|蓝灰色 white|白色 black|黑色
      primary: white
      accent: "white" #强调颜色
      toggle: #切换按钮
         icon: material/weather-night  #暗色模式图标
         name: 切换到暗色模式  #显示名称
    
    - media: "(prefers-color-scheme: dark)" #暗色
      scheme: "slate"
      #主要颜色 red|红色 pink|粉色 purple|紫色 deep-purple|深紫色 indigo|靛蓝色 blue|蓝色 light-blue|浅蓝色 cyan|青色 teal|蓝绿色 lime|黄绿色 deep-orange|深橙色 brown|棕色 grey|灰色 blue-grey|蓝灰色 white|白色 black|黑色
      primary: blue-grey
      accent: "black" #强调颜色
      toggle: #切换按钮
         icon: material/white-balance-sunny #亮色模式图标
         name: 切换到亮色模式 #显示名称

  features:
    - navigation.instant  #现在页面不会跳转,而是类似单页应用,搜索和各种跳转都是在当前页面完成
    - navigation.tabs #页面上方的标签
    - navigation.tracking #页面滚动时,导航栏高亮当前页面
    - navigation.sections #使用导航栏分块
    - navigation.expand #默认展开导航
    - navigation.prune #只渲染当前页面的导航
    - navigation.top #返回顶部按钮
    - navigation.footer #页脚提示下一章
    - toc.follow #滚动时侧边栏跟随
    - search.highlight #搜索结果高亮
    - search.share #分享搜索结果
    - search.suggest #搜索补全建议
    - content.code.copy #代码段上的复制按钮



plugins: #插件选项

  - search   #搜索插件

  - mkdocstrings:  #文档插件
      handlers:
        python:
         
          paths: -src  #这里设置项目的路径

nav: #导航选项
  - 首页: index1.md
  - 前端:
      用户:
        - "注册": "api.md"
        - "退出": "api模板.md"
  - 后端:
      - "登录": "inde.md"
      - "退出": "indse.md"
  - "关于": "about.md"

extra:
  generator: false  #不显示页脚"使用MkDocs 材料制造"
  social: #友情链接
    - icon: material/github
      link: https://github.com/freely-code/server


#下面是开启各种插件和功能
markdown_extensions: #markdown 扩展
  - def_list
  - footnotes #脚注语法
  - abbr
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - md_in_html
  - pymdownx.arithmatex: #Latex支持
      generic: true
  - toc: #生成目录
      permalink: true #固定标题位置为当前位置
      toc_depth: 3 #目录深度
  - pymdownx.highlight: #代码高亮选项
      auto_title: true #显示编程语言
      anchor_linenums: true
      linenums: true #显示行号
      use_pygments: true #使用Pygments
      linenums_style: "pymdownx-inline" #行号样式 table pymdownx-inline

  - pymdownx.caret #上标和下标
  - pymdownx.mark #上标和下标
  - pymdownx.tilde #上标和下标
  - pymdownx.keys #显示按键组合
  - pymdownx.critic 
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.magiclink #自动识别链接
  - pymdownx.smartsymbols #智能符号
  - pymdownx.snippets #代码段
  - pymdownx.details #折叠代码块 
  - attr_list
  
  - pymdownx.emoji: #emoji表情支持
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences: #代码块
      custom_fences: #自定义代码块
        - name: "python" #代码块名称
          class: python #代码块类
          attributes: #代码块属性
            - "linenums" #行号
            - "highlight" #高亮
            - "copy" #复制按钮
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
        alternate_style: true #启用交替样式
        combine_header_slug: true
  - pymdownx.tasklist: #任务列表
      custom_checkbox: true #自定义复选框
      clickable_checkbox: true 
  - meta #支持markdown文件上方自定义标题标签等
  - tables
  


  



      #emoji_folder: "https://cdn.jsdelivr.net/npm/emoji-datasource-apple@14.0.0/img/apple/64" #emoji图片路径
      #emoji_size: 20px #emoji大小
      #emoji_alt: true #emoji是否显示alt属性
      #emoji_unicode: true #emoji是否显示unicode
      #emoji_useimage: true #emoji是否使用图片
      #emoji_generator: "twemoji" #emoji生成器